### PR TITLE
Add markdown v3.2.2 to insurance-requirements

### PR DESCRIPTION
**Pull request by BenBrowne-kWhA**
To support markdown notes for policies in the policy review report.
https://bitbucket.org/kwh/insurance/pull-requests/1433

### CODE REVIEW

**Review by shutton-kwh — APPROVED** [review]

**Comment by abshinn** [comment]
@shutton-kwh Can the dockercloud check be ignored here?

**Comment by shutton-kwh** [comment]
Looks like it’s important and should be fixed before merging. We can see the error detail on https://hub.docker.com/repository/registry-1.docker.io/kwhadocker/data-env/builds/84cb3213-c8c8-4b4e-ba17-5a1347f341c0

**Comment by cscanlin-kwh** [comment]
Newer version of aws-cli drop the requirement for PyYaml. Might be worth trying to update that

**Comment by BenBrowne-kWhA** [comment]
Current error is: 
```
The user requested PyYAML==5.1.2
awscli 1.15.60 depends on PyYAML<=3.13 and >=3.10
```
These two lines are already on master in `marvin-requirements.txt`
```
awscli==1.15.60
PyYAML==5.1.2
````

So I'm confused why the new addition here of
```
Markdown==3.2.2
```

is causing this error... 😕 

Going to try adjusting the awscli version anyway.

**Comment by BenBrowne-kWhA** [comment]
Upgrading awscli doesn't resolve the conflicts:
```
The user requested botocore==1.10.84
awscli 1.18.205 depends on botocore==1.19.45
```

**Comment by abshinn** [comment]
Nice, image build passed. I believe next step is to confirm the additional upgraded requirements will work with our repos, and that will take place when upgraded to image v9 in PRs.

**Review by abshinn — APPROVED** [review]

**Pull request merged**
